# Generated by Django 5.0.1 on 2024-01-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_query_name='product', to='ecommerce.store'),
            preserve_default=False,
        ),
    ]
