# Generated by Django 4.2.6 on 2024-02-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ecommerce', '0005_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='user_role', to='auth.group'),
        ),
    ]
